### ISSUE TITLE
Issue with this MRA (Ninja Princess)

### ISSUE THREAD

**Issue by wwark** [MrX-8B/MiSTer-Arcade-SEGASYS1#2]
Hi,
Maybe there is something missing in this MRA file.
I have garbage with it.
[Ninja Princess (315-5098, 128k Ver.).txt](https://github.com/MrX-8B/MiSTer-Arcade-SEGASYS1/files/3996101/Ninja.Princess.315-5098.128k.Ver.txt)

Thanks,

**Comment by MrX-8B** [comment]
Because the specification etc. are still provisional, Pull Request or Issue is not yet accepted.
