### ISSUE TITLE
Sega Ninja requires a 3rd action button.

### ISSUE THREAD

**Issue by elexor** [MrX-8B/MiSTer-Arcade-SEGASYS1#3]
Some games require a 3rd action button like sega ninja.
https://r.mprd.se/MAME/flyers/seganinj.png

**Comment by MrX-8B** [comment]
Thank you for your report.

I shouldn't rely on my childhood memories...
The date will change just here, so I'll fix it and release it in about three hours.

**Comment by MrX-8B** [comment]
I fixed it and released it.

**Comment by elexor** [comment]
Thankyou so much Mr X you are awesome.
